config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts do
  	resources :likes
  	 resources :comments do
  	  resources :likes
  	    resources :replies do
  		 resources :likes
  	end
  end
end

  get 'posts/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :replies, dependent: :destroy
  has_many :likes, as: :likeable , dependent: :destroy
  validates :comment, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :post, presence: true

	has_many :comments, dependent: :destroy
	has_many :likes, as: :likeable, dependent: :destroy
end

app/models/reply.rb
class Reply < ApplicationRecord
	validates :reply, presence: true
  belongs_to :comment
  has_many :likes, as: :likeable, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  

  def new
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(comment_params)
       redirect_to post_path(@post)
     else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:comment)
    end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts=Post.all
  end

  def new
    @post=Post.new
  end

    def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
 
    if @post.save
       redirect_to @post
    else
      render 'new'
    end

  end

  def update
    @post = Post.find(params[:id])
 
  if @post.update(post_params)
    redirect_to @post
  else
    render 'edit'
  end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
 
  redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:post)
  end

  
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def index
    @replies=Reply.all
  end


  def new
    
    @reply=Reply.new

  end

  def edit
    @post=Post.find(params[:post_id])
    @comment=Comment.find(params[:comment_id])
    @reply=Reply.find(params[:id])
  end

  def create
    @post=Post.find(params[:post_id])
    @comment = @post.comments.find(params[:comment_id])
    @reply = @comment.replies.create(reply_params)
    redirect_to post_path(@comment.post, @comment)
  end

  def update
    @reply=Reply.find(params[:id])
    if @reply.update(reply_params)
      redirect_to post_path(@reply.comment.post)
    else
      render 'edit'
    end
  end

  def destroy
    @reply=Reply.find(params[:id])
     @reply.destroy
      redirect_to post_path(@reply.comment.post)
  end

  private
    def reply_params
      params.require(:reply).permit(:reply)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Comment:</strong>
  <%= comment.comment %><br>
  <% comment.replies.each do |rep| %>
  <p></p><b>Reply:</b>
  <%= rep.reply %>
  <%= link_to 'edit',edit_post_comment_reply_path(rep.comment.post, rep.comment, rep) %>
  <%= link_to 'delete', post_comment_reply_path(rep.comment.post, rep.comment, rep),
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  <% end %>


  
  
</p>
<p>
  
  
</p>

 
 <p>
  <%= link_to 'delete comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>

   <%= link_to 'edit comment',edit_post_comment_path(comment.post, comment) %>
   <%= link_to 'reply comment',  new_post_comment_reply_path(comment.post, comment) %>


 </p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h4>Edit comment:</h4>

<%= form_for([@post, @comment]) do |f| %>
  
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
 
  
    <%= f.submit %>
  
<% end %>

<%= link_to 'Back', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Postcomment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/edit.html.erb
<h1>Likes#edit</h1>
<p>Find me in app/views/likes/edit.html.erb</p>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/likes/show.html.erb
<h1>Likes#show</h1>
<p>Find me in app/views/likes/show.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :post %><br>
    <%= f.text_field :post %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>
<%= link_to 'New post', new_post_path %>
<table>
  <tr>
    <th>Post</th>
    
    <th colspan="3"></th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.post %></td>
      
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
 <h1>Total Comments: <%=@post.comments.count %></h1>
 <p>
  <strong>Post:</strong>
  <%= @post.post %>
</p>
 

 
<h2>Comments</h2>
<%= render @post.comments %>



 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>






 
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Home', posts_path %>

app/views/replies/edit.html.erb
<h4>Edit</h4>

<%= form_for([@post, @comment, @reply]) do |f| %>
  
    <%= f.label :reply %><br />
    <%= f.text_area :reply %>
 
  
    <%= f.submit %>
  
<% end %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= form_for @reply, url: post_comment_replies_path do |f| %>

<p>
    <%= f.label :reply %><br>
    <%= f.text_field :reply %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>